apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.app.backend.image.repo }}:{{ .Values.app.backend.image.tag }}"
        ports:
        - containerPort: 8080
        env:
          {{- include "helpers.list-env-variables" . | indent 10 }}
          - name: CORS
            value: "{{ .Values.app.env.cors }}"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          exec:
            command: ["curl", "-f", "http://localhost:8080/ping"]
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command: ["curl", "-f", "http://localhost:8080/ping"]
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5