apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
spec:
  hosts:
  - "{{ .Values.app.backend.ingress.host }}"
  gateways:
  - backend
  http:
  - match:
    - uri:
        prefix: /api/v1/
    route:
    - destination:
        host: backend
        port:
          number: 80