apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.app.frontend.image.repo }}:{{ .Values.app.frontend.image.tag }}"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          exec:
            command: ["curl", "-f", "http://localhost:3000/"]
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command: ["curl", "-f", "http://localhost:3000/"]
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5